### PR TITLE
Added an animation tutorial

### PR DESCRIPTION
**Pull request by keanine**
Probably needs some editing, but something is better than nothing.

### CODE REVIEW

**Comment by PTKay** [comment]
LGTM! Thank you for your contribution!

**Comment by keanine** [comment]
It looks like the example file names changed to [email protected] on the page for some reason

**Comment by PTKay** [comment]
Everything is looking fine on my end actually.
image

**Comment by keanine** [comment]
That's strange, it looks fine on my end as well now

**Pull request merged**
